{
 "title": "Ping Pong Metrics Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Ping error rate in the last 10 minutes",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(ping_error_count[10m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pong server handle duration of ping request",
   "type": "timeseries",
   "description": "The time taken between the request hitting the /ping handler and the response being sent from the server",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(ping_handler_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(ping_handler_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Mean ping interval",
   "type": "timeseries",
   "description": "The mean interval between pings over the previous 5 minute window.",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(ping_interval_seconds_sum[$__rate_interval])/rate(ping_interval_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration of ping request roundtrip",
   "type": "timeseries",
   "description": "The time between the ping service making a request to the pong service and getting a response back.",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(ping_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(ping_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}