apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'tx-server'
        static_configs:
          - targets: ['tx-server-svc.default.svc.cluster.local:8080']
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-server-conf
            defaultMode: 420
      resources:
        limits:
          memory: 1Gi
          cpu: 1000m
        requests:
          memory: 500Mi
          cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: observability
spec:
  selector:
    app: prometheus-server
  ports:
    - port: 9090
      targetPort: 9090
